### ISSUE TITLE
informatik

### ISSUE THREAD

**Issue by paulhollmann** [sbs-v-plotter/main.python#8]

**Comment by Rotsteinblock** [comment]
Warum?

**Comment by Bug-Patrick** [comment]
Meinst du den?
>  Bug-Patrick assigned Bug-Patrick and unassigned Bug-Patrick 6 minutes ago
Einfach wegen fehlendem Skill mit Github

**Comment by Rotsteinblock** [comment]
nein, das ganze hier, wieso machst du das in unseren github issues?

**Comment by Bug-Patrick** [comment]
Paul und ich probieren zwischen dem Lernen für Informatik die Funktionen von GitHub aus. Falls es wichtig wäre, dass es aufgeräumt ist, machen wir den Quatsch weg.

**Comment by paulhollmann** [comment]
geschafft
